services:
  app:
    container_name: gastometria-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=gastometria
      - NEXT_PUBLIC_DATABASE_TYPE=mongodb
      - NEXT_PUBLIC_AUTH_PROVIDER=mongodb
      - NEXT_PUBLIC_APP_URL=https://gastometria.com.br
      - NEXTAUTH_SECRET=C6CsLT3XoqMGNi4TP88Kv5Dfdi404QUdGMCqHnPd1Kc=
      - NEXTAUTH_URL=https://gastometria.com.br
      - AUTH_TRUST_HOST=true

  mongo:
    container_name: gastometria-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
